### ISSUE TITLE
Segmentation fault when using with fzf

### ISSUE THREAD

**Issue by David-Else** [folke/zen-mode.nvim#1]
I am afraid that I get a segmentation fault with it and `fzf.vim`/`fzf`.

1. open fzf history with `:History!`, open a file
2. toggle zen mode on
3. open fzf history with `:History!`, open a file

`Segmentation fault (core dumped)`

`NVIM v0.5.0-dev+1326-ge0a01bdf7` (latest today)

**Comment by folke** [comment]
Have you tried opening FZz multiple times without starting zen Mode? Today's built might be broken.

Either way, segmentation faults like this can not be caused by a lua plugin. This means something funky is going on inside the neovim code base. Most likely related to the new z-index in this case.

**Comment by David-Else** [comment]
I did try `:History!` many times with your plugin disabled and it works fine.

**Comment by folke** [comment]
I'll look into it somewhere tomorrow.

**Comment by folke** [comment]
I was able to reproduce this and created an [issue](https://github.com/neovim/neovim/issues/14578) in Neovim

**Comment by David-Else** [comment]
@folke This bug seems to have changed with latest Neovim/zen-mode:

 - open fzf history with :History!, open a file
-  toggle zen mode on
 - open fzf history with :History!

Now zen mode closes suddenly and fzf does not open, instead you are left with the remains of a fzf window:

```
t//~/D/p/p/f//4/h/d/d/n/.c/n/p/f/b/f/h/d/d/n/.c/n/p/f/b/p/:/t/n/3;#FZF  filename.md 
```
