### ISSUE TITLE
Integration with lspconfig and lspsaga

### ISSUE THREAD

**Issue by AckslD** [folke/zen-mode.nvim#10]
Similarly to the `gitsigns` plugin, is there an integration with lsp to disable eg virtual text diagnostics and code action prompt from `lspsaga` in zen mode?

**Comment by folke** [comment]
Great idea. I'll add this soon. Thanks!

**Comment by benbrastmckie** [comment]
Could this happen by running a command in here:
```
    on_open = function(win)
        COMMAND TO KILL LSP
    end,
    on_close = function()
        COMMAND TO RESTART LSP
    end,
```
I ask because I'm not totally sure what should go in for the placeholders above. Any pointers would be great.

**Comment by mahlonsmith** [comment]
> I ask because I'm not totally sure what should go in for the placeholders above. Any pointers would be great.

```lua
on_open = function(win)
	vim.cmd("LspStop")
end,

on_close = function()
	vim.cmd("LspStart")
end
```

... works great.
