### ISSUE TITLE
bug: OSC8 support fails

### ISSUE THREAD

**Issue by agenbite** [folke/zen-mode.nvim#100]
### Did you check docs and existing issues?

- [X] I have read all the zen-mode.nvim docs
- [X] I have searched the existing issues of zen-mode.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.0-dev-1236+g28ffd96c9    

### Operating system/version

Ubuntu 23.04

### Describe the bug

I'm a happy user of zen-mode in combination with page (to use nvim as a pager). Everything works fine except for the OSC8 hyperlinks, which are broken when zen-mode is active. This is not convenient for seeing emails, for example. Has anyone found this issue and maybe a solution? 

### Steps To Reproduce

0. Launch a terminal emulator (tried in alacritty, kitty and xfce4-terminal)
1. Launch nvim
2. :ZenMode
3. Open a new buffer and write or copy a long URL (i.e.: https://www.longurlthatmight.be/wrapped/on/the/edges/if/the/terminal/is/not/very/wide
4. Hover your mouse or use the hints from your terminal (CTRL-SHIFT-U, in Alacritty) and the URL is not recognised.

### Expected Behavior

I would expect my terminal to recognise the URLs inside ZenMode, independently of where they're cut on screen.

**Comment by folke** [comment]
I don't see how this could be a zen-mode issue, since all zen-mode does is show the buffer in a floating window.
If you're certain this is an issue, then create a minimal repro (without using zen-mode) and submit an issue upstream.
