### ISSUE TITLE
feature: incline plugin/support

### ISSUE THREAD

**Issue by vyorkin** [folke/zen-mode.nvim#106]
### Did you check the docs?

- [X] I have read all the zen-mode.nvim docs

### Is your feature request related to a problem? Please describe.

I expected this line below to work as intended:
```lua
  on_open = function()
    incline.disable()
  end,
  on_close = function()
    incline.enable()
  end,
```
But when zenmode opens all of incline statuslines are visible (for all of my opened split windows), like on the screenshot:
<img width="1265" alt="image" src="https://github.com/folke/zen-mode.nvim/assets/988849/1c1f363b-aa23-467d-ac2c-bf2fc5eb4382">

### Describe the solution you'd like

I'd like to be able to disable `incline` when I toggle the zenmode and enable it when I exit zen.

### Describe alternatives you've considered

I don't know about any good alternatives

**Comment by vyorkin** [comment]
Just noticed that setting `window = { zindex = 10 }` in `incline` options helps with this

**Comment by joshmedeski** [comment]
I'm having the same issue, running `:lua require("incline").disable()` works manually but when put in my zen-mode `on_open` hook nothing happens.

**Comment by folke** [comment]
Your code should work.
Just tested myself and seems to be an issue with incline.

On disable, the styling of the winbar is reset and on enable, my incline styles come back.

No idea why, but this is not a zen-mode issue

**Comment by joshmedeski** [comment]
Thanks @folke, I submitted a ticket with incline to further investigate.
