### ISSUE TITLE
feature: disable Zen Mode when opening command-line window

### ISSUE THREAD

**Issue by asterixpound** [folke/zen-mode.nvim#107]
### Did you check the docs?

- [X] I have read all the zen-mode.nvim docs

### Is your feature request related to a problem? Please describe.

When ZenMode is active, opening the command-line window with either `q:` from normal mode or `<C-f>` from Vim's command-line does not result in a visible command-line window.

### Describe the solution you'd like

It would be nice if ZenMode toggled off when opening the command-line window in the same way as it does when opening a split pane.

### Describe alternatives you've considered

Of course, you could disable ZenMode manually before opening the command-line manually but it would be nice if this happened automatically.

**Comment by whompyjaw** [comment]
I think it would be better if we could run command mode while using zenmode. I would personally prefer just to center _all_ my buffers. command, netrw, automatically
