### ISSUE TITLE
Zen Mode doesn't disable Gitsigns

### ISSUE THREAD

**Issue by rafamadriz** [folke/zen-mode.nvim#11]
Hey, thanks you this amazing plugin. 

Gitsigns are not being disable, I'm just using the default config. Which is supposed to disable gitsigns by default.

![2021-May-20_1](https://user-images.githubusercontent.com/67771985/119074344-5d0ddd00-b9de-11eb-9eb4-6e0d1eed91f0.png)

I'm don't have any custom settings , just installed the plugin and use it as it comes, also tried copying the [default config](https://github.com/folke/zen-mode.nvim#%EF%B8%8F--configuration) from the README into my `init.lua` but that didn't work either.

I also updated with `:PackerSync` but still nothing, the gitsigns are still there.

**Comment by folke** [comment]
You need to enable the gitsigns plugin to hide it. It is disabled by default. See the docs

**Comment by rafamadriz** [comment]
Oh my bad, in the docs it says `gitsigns = { enabled = false }` I thought it meant that it was disabled by default, not the other way around. Thanks!

**Comment by folke** [comment]
That means the gitsigns integration is enabled. Confusing, I know :)
