### ISSUE TITLE
feature: Zellij Support

### ISSUE THREAD

**Issue by agluck91** [folke/zen-mode.nvim#112]
### Did you check the docs?

- [X] I have read all the zen-mode.nvim docs

### Is your feature request related to a problem? Please describe.

NA

### Describe the solution you'd like

I would like to see support for zellij that is similar to the tmux support that exists today. 

### Describe alternatives you've considered

NA

### Additional context

NA

**Comment by meicale** [comment]
I think zellij support will be quite good!
