### ISSUE TITLE
bug: incompatable with Trouble outline

### ISSUE THREAD

**Issue by idelice** [folke/zen-mode.nvim#127]
### Did you check docs and existing issues?

- [X] I have read all the zen-mode.nvim docs
- [X] I have searched the existing issues of zen-mode.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.5

### Operating system/version

mac 14.3

### Describe the bug

Opening Trouble outline while in zenmode will toggle zenmode off and Trouble outline not being shown. they are just not working together

### Steps To Reproduce

1. toggle zenmode
2. toggle Trouble outline

### Expected Behavior

I expect zenmode not being toggled off when opening trouble outline.

**Comment by b0ae989c** [comment]
Duplicate of #120. Should close.

**Comment by idelice** [comment]
@b0ae989c  Updated ticket to reflect Trouble outline instead.

**Comment by folke** [comment]
There's no `:Trouble outline`.
If you mean document symbols than that works for me, but of course it won't be shown in the zen window.
And you should have `focus=false` (which is the default).

Closing, since it doesn't really make sense to use trouble from zen mode.
