### ISSUE TITLE
feature: Add option to keep bufferline.nvim on

### ISSUE THREAD

**Issue by gerazov** [folke/zen-mode.nvim#128]
### Did you check the docs?

- [X] I have read all the zen-mode.nvim docs

### Is your feature request related to a problem? Please describe.

Great plugin! :sunglasses:

I frequently use zen-mode to center text for editing. I usually edit latex documents that input other `tex` files and have several buffers open at a time. In this scenario I find using [akinsho/bufferline.nvim](https://github.com/akinsho/bufferline.nvim) very convenient when moving around open buffers sequentially. 

In zen-mode the bufferline is turned off by default.

### Describe the solution you'd like

It would be useful to be able to keep `bufferline.nvim` active when in Zen mode as an option.

### Describe alternatives you've considered

/

**Comment by iafshinafshin** [comment]
Hello,   **Yes , I have request looks like this feature too**

**Comment by b0ae989c** [comment]
We don't need to add new features. This is achievable with `on_open`. For example,
```lua
{
  "folke/zen-mode.nvim",
  opts = {
    on_open = function(win)
      local view = require("zen-mode.view")
      local layout = view.layout(view.opts)
      vim.api.nvim_win_set_config(win, {
        width = layout.width,
        height = layout.height - 1,
      })
      vim.api.nvim_win_set_config(view.bg_win, {
        width = vim.o.columns,
        height = view.height() - 1,
        row = 1,
        col = layout.col,
        relative = "editor",
      })
    end,
  },
},
```

**Comment by gerazov** [comment]
Works great - thanks! :pray: 

It could be useful to add this as an example use-case in the docs?

**Comment by gerazov** [comment]
I've updated the code to check if `bufferline` is active, since I have it lazy load on `BufAdd`, i.e. only when multiple buffers are open.

```lua
on_open = function(win)
  local buffline = package.loaded["bufferline"]
  if buffline then
    local view = require("zen-mode.view")
    local layout = view.layout(view.opts)
    vim.api.nvim_win_set_config(win, {
      width = layout.width,
      height = layout.height - 1,
    })
    vim.api.nvim_win_set_config(view.bg_win, {
      width = vim.o.columns,
      height = view.height() - 1,
      row = 1,
      col = layout.col,
      relative = "editor",
    })
  end
end,
```

**Comment by iafshinafshin** [comment]
Hello, these codes does not work for me, :(

**Comment by gerazov** [comment]
I have it in my `config` function, but it shouldn't make a difference :thinking: 
```lua
return {
  "folke/zen-mode.nvim",
  enabled = true,
  lazy = true,
  event = 'verylazy',
  config = function ()
    require "zen-mode".setup {
      on_open = function(win)
        local buffline = package.loaded["bufferline"]
        if buffline then
          local view = require("zen-mode.view")
          local layout = view.layout(view.opts)
          vim.api.nvim_win_set_config(win, {
            width = layout.width,
            height = layout.height - 1,
          })
          vim.api.nvim_win_set_config(view.bg_win, {
            width = vim.o.columns,
            height = view.height() - 1,
            row = 1,
            col = layout.col,
            relative = "editor",
          })
        end
      end,
    }
  end
}
```

**Comment by james-gour** [comment]
@gerazov any way to center the bufferline as well ? :)

**Comment by gerazov** [comment]
Ahah  :) 

This should be by setting some option in the bufferline. It has `offsets` in the setup function and this has a parameter `padding` but you have to dig into the code to find how to access the bufferline drawing API.
