### ISSUE TITLE
feature: Warp Support

### ISSUE THREAD

**Issue by jellydn** [folke/zen-mode.nvim#129]
### Did you check the docs?

- [X] I have read all the zen-mode.nvim docs

### Is your feature request related to a problem? Please describe.

I'd like to support https://docs.warp.dev/ as a plugin in the same way we have for other terminals.

### Describe the solution you'd like

Something like this

```lua
      plugins = {
        warp = {
          enabled = true,
          font = "+1", -- +1 font size or fixed size, e.g. 21
        },
      },
```

### Describe alternatives you've considered

N/A

**Comment by ekorchmar** [comment]
I don't think Warp exposes any API that would make it feasible.
