### ISSUE TITLE
feature: Allow disabling LazyVim's scope-matching vertical line

### ISSUE THREAD

**Issue by eulersson** [folke/zen-mode.nvim#136]
### Did you check the docs?

- [X] I have read all the zen-mode.nvim docs

### Is your feature request related to a problem? Please describe.

The visual vertical lines that match the scope of your function can be distracting (I apologize because I don't know what config option or plugin in LazyVim is creating it).

<img width="1319" alt="image" src="https://github.com/folke/zen-mode.nvim/assets/6486812/c0076649-c24d-4124-b77a-042fd968c6a9">

### Describe the solution you'd like

I would like to configure it to be disabled, both when the vertical line is highlighted and when it isn't.

### Describe alternatives you've considered

None.

### Additional context

I apologize because I do not know who is responsible for the vertical line. I tried playing with all existing options in folke's plugin without success.

**Comment by sjclayton** [comment]
@eulersson 

This is handled by this plugin --> https://github.com/lukas-reineke/indent-blankline.nvim

**Comment by timrosu** [comment]
If you want to disable it completely in zen-mode, you can add `vim.cmd("silent! IBLDisable")` to on_open function and `vim.cmd("silent! IBLEnable")` to on_close.
