### ISSUE TITLE
Makes coc.nvim's signatureHelp go to whole unexpected places

### ISSUE THREAD

**Issue by oblitum** [folke/zen-mode.nvim#14]
Hi, thanks for great plugin. I'm didn't yet move to nvim-lsp, so, just wanna report that it's incompatible with coc.nvim:

![img-2021-05-23-233305](https://user-images.githubusercontent.com/1269815/119288654-5cb05480-bc1f-11eb-82c6-b243a6df2576.png)

**Comment by folke** [comment]
We don't to anything special here, so it seems Coc is not compatible with the new floating windows in Neovim 0.5. 
You should file an issue about this with coc.

Closing this as this is not a zen-mode issue.

**Comment by folke** [comment]
Before the `zindex` patch of a week ago, popups acted weird with each other. I assume coc tries to position its  popups next to other popups, but with the zindex patch that's no longer needed. But again, not a `zen-mode` issue ;)

**Comment by oblitum** [comment]
Thanks for the info.

**Comment by oblitum** [comment]
@folke fyi, same issue with other plugins, like vim-matchup for example:

![17:11:48_02-06-2021](https://user-images.githubusercontent.com/1269815/120545965-acccab00-c3c5-11eb-9d7d-654ef150c88e.png)

**Comment by folke** [comment]
This is due to https://github.com/neovim/neovim/issues/14735

**Comment by oblitum** [comment]
Fixed on nvim 0.5.1 :)
