### ISSUE TITLE
Typewrite-like centered writing

### ISSUE THREAD

**Issue by nounder** [folke/zen-mode.nvim#147]
### Did you check the docs?

- [X] I have read all the zen-mode.nvim docs

### Is your feature request related to a problem? Please describe.

It would be amazing to have typewrite-like experience by moving beginning of the document to the middle of the window. As words are written, new lines are always centered to the middle. Please see video below:

![screenshot-2024-07-30T020707](https://github.com/user-attachments/assets/952c7790-f3d3-4139-8181-416cbd2b48b1)

### Describe the solution you'd like

A typewriter flag option to enable this type of writing experience.

### Describe alternatives you've considered

Using iA Writer instead of nvim? :sad:

**Comment by b0ae989c** [comment]
We don't need a new feature for this. Setting `scrolloff` to a large number will do. For example,
```lua
opts = {
  window = {
    options = {
      scrolloff = 999,
    },
  },
},
```

**Comment by nounderline** [comment]
I tried that but there was no change whatsoever. Doing `:set scrolloff 999` directly did nothing, too. What should be result of setting this option?

**Comment by nounderline** [comment]
Just tried running `nvim -u NONE` with plain config and setting `scrolloff` doesn't seem to do anything.

**Comment by b0ae989c** [comment]
It's `:set scrolloff=999`.

**Comment by b0ae989c** [comment]
Either your config does not respect `scrolloff`, or your file does not have enough lines of visible text to satisfy `scrolloff` setting. The later is documented:

```
'scrolloff' 'so'        number  (default 0)
                        global or local to window global-local
        Minimal number of screen lines to keep above and below the cursor.
        This will make some context visible around where you are working.  If
        you set it to a very large value (999) the cursor line will always be
        in the middle of the window (except at the start or end of the file or
        when long lines wrap).
```

**Comment by nounderline** [comment]
`scrolloff` documents desired behavior but it doesn't seem to work at all. I tested it on long files (>400 lines) with nvim 0.10 and 0.9.5 on three independent workstations.

**Comment by nounderline** [comment]
`scrolloff` does not what it described and shown in the original comment. It scrolls the text so that (when possible) there are always at least five lines visible above the cursor, and five lines visible below the cursor.

**Comment by danrasmuson** [comment]
I would love a feature like this. Any other suggestions or plans to support this kind of functionality in zen-mode?

**Comment by Zimzozaur** [comment]
Was it abandoned?
