### ISSUE TITLE
Zen mode forgets the changelist of the previous window

### ISSUE THREAD

**Issue by smithbm2316** [folke/zen-mode.nvim#15]
I'm not sure if this is easily tackleable, however it is something that I would love to be added to zen-mode. I'd be happy to look into implementing this myself sometime in the coming week or two, as I use the `g;` command a lot to jump to my most recent edit. However when I toggle zen mode on/off, because it puts it in a new floating buffer the changelist of the previous window is forgotten. I'm mostly putting this here as a reminder to myself to look into trying to find a workaround to push as a PR for this, as I doubt many people use the `g;` command as heavily as I do. Thanks for all of your hard work on this plugin, lua-dev.nvim, and tokyonight! I've been loving using all of the above on a daily basis :smile:

**Comment by folke** [comment]
Definitely a bug it seems. If you make a single edit in the zen window, then the changelist works again.

**Comment by folke** [comment]
update: the changelist works, but your position in the list hs been reset to the first change
