### ISSUE TITLE
feature: Add option to disable "exit ZenMode when clicking outside of the focus panel" behavior

### ISSUE THREAD

**Issue by alichtman** [folke/zen-mode.nvim#151]
### Did you check the docs?

- [X] I have read all the zen-mode.nvim docs

### Is your feature request related to a problem? Please describe.

I have mouse support enabled in neovim (`:set mouse=nvi`). When I click outside of the ZenMode panel, ZenMode is automatically exited.

### Describe the solution you'd like

 I'd like to be able to disable this behavior, and didn't see it mentioned in the docs / config options. 

### Describe alternatives you've considered

n/a

**Comment by b0ae989c** [comment]
This is expected. See line 208 in https://github.com/folke/zen-mode.nvim/blob/29b292bdc58b76a6c8f294c961a8bf92c5a6ebd6/lua/zen-mode/view.lua#L201-L213

The intended behavior is that when you enter a non-float window (with mouse click in this case), `on_win_enter` gets invoked and zen-mode will exit.

**Comment by kusnezoff-alexander** [comment]
+1. Is there any work-around for disabling the automatic exit of `ZenMode`? I would like `ZenMode` to exit only after it was manually instructed to do so (via `:ZenMode/:close/...`).
