### ISSUE TITLE
bug: On quitall (:qa) in zen floating window, the terminal stick with +n fontsize

### ISSUE THREAD

**Issue by componhead** [folke/zen-mode.nvim#152]
### Did you check docs and existing issues?

- [X] I have read all the zen-mode.nvim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of zen-mode.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.0 Build type: Release LuaJIT 2.1.1716656478

### Operating system/version

Sonoma 14.6.1

### Describe the bug

terminal type: wezterm (with modified cfg)

### Steps To Reproduce

1. enter zen mode with font +n
2. quitall (:qa)

### Expected Behavior

Terminal should have -n zenmode font size

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    { "folke/zen-mode.nvim", opts = {} },
    -- add any other plugins here
  },
})
```

**Comment by b0ae989c** [comment]
This is not a bug. Plugin states get reset via `plugins_on_close`. If you don't call `require('zen-mode').close()` or `require('zen-mode').plugins_on_close()`, plugin states won't get reset.

Workaround:
```lua
vim.api.nvim_create_augroup('ZenModeFix', { clear = true })
vim.api.nvim_create_autocmd({ 'VimLeavePre' }, {
  group = 'ZenModeFix',
  callback = function() require('zen-mode').close() end,
})
```
