### ISSUE TITLE
LSP diagnostics and signature popup window has wrong background colour

### ISSUE THREAD

**Issue by David-Else** [folke/zen-mode.nvim#16]
Correct:
![Screenshot from 2021-06-03 10-02-06](https://user-images.githubusercontent.com/12832280/120618619-26f74100-c453-11eb-80b4-525c7b0eb5a2.png)
In zen mode there are grey bars on the left and right of the diagnostic window, and the background is now black instead of grey:
![Screenshot from 2021-06-03 10-03-25](https://user-images.githubusercontent.com/12832280/120618654-2e1e4f00-c453-11eb-8e84-b7090bfcb5aa.png)
also the exact same thing with the signature completion:
![Screenshot from 2021-06-03 10-08-01](https://user-images.githubusercontent.com/12832280/120619175-a7b63d00-c453-11eb-90db-8efb721d9d2e.png)

I am using:
```
-- Show diagnostics on cursor over
vim.cmd [[autocmd CursorHold * lua vim.lsp.diagnostic.show_line_diagnostics()]]
-- Show function signature help while typing
vim.cmd [[autocmd CursorHoldI * silent! lua vim.lsp.buf.signature_help()]]
```

**Comment by timsofteng** [comment]
I have same issue.

**Comment by folke** [comment]
There's something weird going on with `nvim_win_set_option`. It doesn't behave the same as `:setlocal`.
Changed it to `:setlocal`. Can you confirm this is fixed now?

**Comment by timsofteng** [comment]
@folke no
It looks now even worse...

![image](https://user-images.githubusercontent.com/51912173/122399997-f6032a00-cf83-11eb-8663-6f94cc2e53dc.png)

colorscheme - gruvbox.nvim

**Comment by folke** [comment]
@timsofteng the float seems to have the correct float bg defined in your colorscheme, no?
Doesn;t the lsp popup look the same as if you would open it from a regular file?

**Comment by folke** [comment]
If you would like the backdrop to have the same hl group as Normal, then I can make that optional. Right now it simply uses the default `NormalFloat` hl group

**Comment by timsofteng** [comment]
> If you would like the backdrop to have the same hl group as Normal, then I can make that optional. Right now it simply uses the default `NormalFloat` hl group

It was black before... IDK but it was better. I guess it was even darker than my main background. So I would prefer it I guess.

BTW I find another bug on `go-to-definition`


https://user-images.githubusercontent.com/51912173/122401772-9279fc00-cf85-11eb-9ec0-b46719dbb325.mp4

**Comment by timsofteng** [comment]
> @timsofteng yep, you're right. Should both be fixed now. Can you check?

Looks like both issues fixed!
Phenomenal.
Thanks a lot!

**Comment by folke** [comment]
Great to hear. Closing this

**Comment by David-Else** [comment]
I checked, it is fixed, cheers! :)
