### ISSUE TITLE
issue: CPU spike in zen mode lazyvim distro

### ISSUE THREAD

**Issue by bl11y** [folke/zen-mode.nvim#165]
### Did you check docs and existing issues?

- [X] I have read all the zen-mode.nvim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of zen-mode.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10.2

### Operating system/version

MacOS 14.7.1

### Describe the bug

It seems like my cpu spikes from 2.3% for neovim to over 40% when in zen mode with all the defaults that lazyvim set (dimming, etc).

I am on kitty terminal if that helps.
Has anyone found the same?

### Steps To Reproduce

1. check activity monitor or equivalent and check neovim process cpu usage
2. start zen mode
3. watch neovim cpu usage spike up 

### Expected Behavior

High cpu spike is it expected?

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    { "folke/zen-mode.nvim", opts = {} },
    -- add any other plugins here
  },
})
```

**Comment by btctrl** [comment]
feel free to close if meant to be or unreproducible

I haven't tied it down the zen mode 100%
I just see cpu usage spike high as soon as zen mode is on

I'm also running a transparent background
Though zen mode immediately still spikes the cpu

nvim starts at 2-3% and jumps to 45%

**Comment by folke** [comment]
Yeah, sorry, but really can't reproduce this
