### ISSUE TITLE
tmux in kitty

### ISSUE THREAD

**Issue by helmecke** [folke/zen-mode.nvim#18]
Hi,

if both `kitty` and `tmux` are enabled. Font size increase is not set if ZenMode is toggled in `tmux` in `kitty`. Font increase works if `nvim` is started directly in `kitty`. Statusline toggle in `tmux` also works.

```lua
plugins = {
  tmux = { enabled = true }, -- disables the tmux statusline
  kitty = {
    enabled = true,
    font = "+4", -- font size increment
  },
},
```
Great plugin, thank you!

**Comment by folke** [comment]
What do you get when you do `echo $KITTY_LISTEN_ON` within tmux?

Your tmux session must be started within Kitty to have the correct socket to communicate with kitty

**Comment by helmecke** [comment]
That was indeed the problem. I've added `set -ga update-environment 'KITTY_LISTEN_ON'` to `~/.tmux.conf`. That fixed the it.

Thank you very much!

**Comment by ned-si** [comment]
Hey there, 

Amazing plugin and everything is working perfectly except this.

Exact same issue on my side, but the fix didn't work for me. I have the following:

In `zen-mode.lua`:
```lua
    tmux = { enabled = true }, -- disables the tmux statusline
    kitty = {
      enabled = true,
      font = "+10", -- font size increment
    },
```

In `kitty.conf`:
```
allow_remote_control socket-only
listen_on unix:/tmp/kitty
```

And in `tmux.conf`:
```
set -ga update-environment 'KITTY_LISTEN_ON'
```

But the resizing still doesn't work.

Any idea what could be happening and how to fix it?

[Here](https://github.com/ned-si/dotfiles) are my dotfiles if needed.j
I
