### ISSUE TITLE
`require("gitsigns")._get_config()` is now deprecated

### ISSUE THREAD

**Issue by Pocco81** [folke/zen-mode.nvim#20]
Hey @folke! just wanted to let you know that [this](https://github.com/folke/zen-mode.nvim/blob/main/lua/zen-mode/plugins.lua#L5) is depracted (or will eventually be). I raised an issue in the authors' repo about exposing the config and he made [this](https://github.com/lewis6991/gitsigns.nvim/issues/167#issuecomment-830643901), which is what you are using now.

15 days ago (at the time of writing) he commented back [this](https://github.com/lewis6991/gitsigns.nvim/issues/167#issuecomment-861586038) saying that there was a newer way of getting the config and that he was going to remove the older method eventually:

> I plan to remove _get_config() soon just to be warned

I'm not sure if it's gone now, but you should probably update that as soon as possible :+1:

**Comment by folke** [comment]
Thanks for letting me know! I'll fix it.

**Comment by folke** [comment]
All fixed now. thanks again for letting me know! :)
