### ISSUE TITLE
highlighting of current indention level

### ISSUE THREAD

**Issue by ipatch** [folke/zen-mode.nvim#23]
i'm a little behind the curb in keeping up with the latest neovim, but did notice in your README that you have highlighting of your current indention level when working with nested indention and indent lines.

is the highlighting specific to neovim ≥ 0.5 or can it be achieved with neovim 0.43 ? or it specific to this plugin? i viewed several source files but didn't see anything that jumped out at me. (no pun)

**Comment by folke** [comment]
I use https://github.com/lukas-reineke/indent-blankline.nvim/ for this :)

**Comment by ipatch** [comment]
thanks. 🙏
