### ISSUE TITLE
`window.width` not quite matching the `col` setting

### ISSUE THREAD

**Issue by evantravers** [folke/zen-mode.nvim#24]
I've got my `colorcolumn` set to 80, and `window.width` set to 80 and the resulting window doesn't line up.

I'm going to do some more robust testing, but I _think_ that the width calculation doesn't include the linenumber column… on files with 100+ lines, it's off by three characters.

**Comment by Hubro** [comment]
This sounds like expected behavior to me. If I configure the Zen window width to be 80 columns, I wouldn't expect it to fit a 80 line-length file + line numbers + gutter symbols. Why not just set it to something like 90 instead? :slightly_smiling_face:
