### ISSUE TITLE
Allow width / height to take functions that return a number

### ISSUE THREAD

**Issue by tjdevries** [folke/zen-mode.nvim#25]
Since I sometimes have font size very small (when I'm working) and sometimes very big (when I'm streaming), it'd be nice to be able to have the default for `width` and `height` to be able to take a function that returns a number, so I can dynamically calculate the dimensions of the window.

I do this here: https://github.com/nvim-telescope/telescope.nvim/blob/master/lua/telescope/config/resolve.lua and would definitely consider moving this code out of here -> plenary if you wanted to re-use it and we thought it could be useful as a more general tool.

I think it's quite a fun little module :)

**Comment by folke** [comment]
I just pushed an [update](https://github.com/folke/zen-mode.nvim/commit/809d0de7adeaf85d482b2b98532ee596d7cc9921) that implements this. Have fun with it :)
