### ISSUE TITLE
Number option fails to work

### ISSUE THREAD

**Issue by lokesh-krishna** [folke/zen-mode.nvim#26]
Copying the default config into my `init.vim` and editing it just to uncomment the number option, it fails to disable the numbers column even though `number = false`.

**Comment by drzhivago420** [comment]
Same. I've tried both = false and = "false", and inside and outside of window = {}
Seems like the most important option to have functioning properly imo

**Comment by 7ze** [comment]
any updates on this?

**Comment by folke** [comment]
```lua
      require("zen-mode").setup({
        window = {
          options = {
            number = false,
            relativenumber = false,
          },
        },
})
```
