### ISSUE TITLE
Provide on_open_pre, on_open_post, on_close_pre and on_close_post?

### ISSUE THREAD

**Issue by oblitum** [folke/zen-mode.nvim#28]
Hi. I wish to toggle `xiyaowong/nvim-transparent` OFF before entering ZenMode, and ON when exiting it. The currently provided hooks `on_open` and `on_close` are not working exactly as I wish. I need to `require('transparent').toggle_transparent(0)` before zen-mode.nvim applies any of its settings, otherwise I lose backdrop due to transparent background (zen-mode.nvim should not know about previous transparency at all and work as if I was just using opaque background). I had similar issues with Goyo and maintained a fork with a bunch of fixes, one of those was having clearer hooks `on_open_pre`, `on_open_post`, `on_close_pre` and `on_close_post`.

**Comment by oblitum** [comment]
Closing for now. It seems this isn't relevant in this transparency case, I tried to move `on_open` call up and down but it did not have any effect to bring back backdrop, it always vanishes when `toggle_transparent` is called.

**Comment by oblitum** [comment]
Seems these two plugins are plain incompatible regarding backdrop. Calling `:TransparentToggle` once and then toggling it off will cause backdrop not work anymore.

**Comment by Odas0R** [comment]
Hey don't know if you got any answer, but for some if have this problem

```vimscript
highlight ZenBg guibg=NONE ctermbg=NONE
```
