### ISSUE TITLE
Treesitter error on empty buffer and markdown files

### ISSUE THREAD

**Issue by LuisxSullivaN** [folke/zen-mode.nvim#29]
Maybe I'm ignoring something, but when I run ZenMode with a markdown file it throws me this error: 
```
Error detected while processing WinScrolled Autocommands for "*":
E5108: Error executing lua /usr/share/nvim/runtime/lua/vim/treesitter/language.lua:25: no parser for 'markdown' language, see :help treesitter-parsers
```
And as far as I know there is no parser for markdown on neovim's treesitter.

Also when opening ZenMode on empty buffer it shows this:
```
Error detected while processing WinScrolled Autocommands for "*":
E5108: Error executing lua Failed to load parser: uv_dlopen: /home/luis/.local/share/nvim/site/pack/packer/start/nvim-treesitter/parser/.gitignore: file too short
```
I'm using neovim latest version 0.5.0 from the Arch Linux official repo

If the problem is on me, I'd appreciate any help. Thanks in advance.

**Comment by folke** [comment]
I actually pushed a fix for this yesterday to Twilight.
