### ISSUE TITLE
Cursor jumps one line down when opening ZenMode

### ISSUE THREAD

**Issue by AnatoleLucet** [folke/zen-mode.nvim#33]
When I open ZenMode, the cursor seems to jump one line down each time.

I assume you're setting the cursor's position in the new buffer based on where the cursor was before opening ZenMode. But if it's really the case, I can't figure out where this is in the code.
I can try to fix this, but I might need a bit of help to find out where / how the cursor position is set in the code :slightly_smiling_face:

**Comment by folke** [comment]
I can't reproduce this. I also don't do anything special with the current line when the zen window opens. Probably something else in your config that triggers this behavior.
