### ISSUE TITLE
tmux status not being disabled when entering zen mode

### ISSUE THREAD

**Issue by surmish** [folke/zen-mode.nvim#4]
I just built the nightly, and am using nvim within tmux (zsh shell).
Isn't tmux status disable the defautl?

**Comment by coinator** [comment]
No, you need to add `plugins = { tmux = true}` to the config

**Comment by rorj** [comment]
Documentation suggests that tmux status line is disabled by default, but it's not.

**Comment by folke** [comment]
@rorj @surmish you're right. The default settings were not correct in the README. I've updated the readme to reflect this.

**Comment by surmish** [comment]
Thank you both! Thanks also for the well thought out plugin. I have another quick question, do you know how to disable line numbers on entering zen mode? (And perhaps, restoring them (if they were enabled before) on exiting)

**Comment by folke** [comment]
@surmish  uncomment the `number=false` and `relativenumber`

![image](https://user-images.githubusercontent.com/292349/118602877-1a42cf80-b768-11eb-9519-ab5d9596ea2f.png)

**Comment by surmish** [comment]
thanks, should've read the documents properly

**Comment by jabuxas** [comment]
running the commands here the font size does increase https://github.com/folke/zen-mode.nvim/blob/main/lua/zen-mode/plugins.lua#L40-L43

`kitty @ --to unix:/tmp/kitty-1073 set-font-size +5`
