### ISSUE TITLE
[BUG?] ZenMode doesnt disable GitSigns

### ISSUE THREAD

**Issue by druskus20** [folke/zen-mode.nvim#41]
Similarly to #11, entering ZenMode doesnt disable gitsigns for me. I've tried both gitsigns `enabled = true` and `enabled = false` just in case, but it doesnt make a difference. I've also tried loading the plugin after gitsigns in my packer config. The plugin that Im using is `lewis6991/gitsigns.nvim`.
Changing other settings like `width` or `twilight` work propperly. 

![image](https://user-images.githubusercontent.com/43417195/136816467-15384a83-bf03-4c83-89d2-8a9c3fdf8e7b.png)

PD: Im using Aniseed to configure vim in fennel. It should't make a difference at all.

**Comment by tin-pham** [comment]
same problem

**Comment by folke** [comment]
plugins shouldn't be under window. Please check the docs

**Comment by druskus20** [comment]
True, completely my bad sorry
