### ISSUE TITLE
Height in zen-mode doesn't change after decreasing font in kitty

### ISSUE THREAD

**Issue by darteil** [folke/zen-mode.nvim#45]
Hello!
After reducing the font in kitty, large gaps appear at the top and bottom in zen-mode.
![2021-11-10_17-12](https://user-images.githubusercontent.com/31193144/141095859-13c5bcbb-6438-48da-b563-c651786d048e.png)

Screencast:

https://user-images.githubusercontent.com/31193144/141095926-9a996257-9331-46d4-8f45-3554f04e702c.mp4

Is it possible to make the zen-mod open to its full height after decreasing font in kitty?

**Comment by lervag** [comment]
I believe I have a similar issue, where I use `on_open` to call `xdgtool` to toggle my terminal full screen. Perhaps a solution could be to add an `on_open_pre` callback (used by kitty as well) that is called _before_ zen mode creates the floating windows?

**Comment by Hubro** [comment]
Zen already fixes the layout on the `VimResized` event:

https://github.com/folke/zen-mode.nvim/blob/9ae43df6ee4d6c3d47aea057086c9e56fca58234/lua/zen-mode/view.lua#L190

So my guess is that Neovim fails to emit that event in this case. I would suggest you set up an autocommand to test the `VimResized` event and see if it triggers when you change font size. If it doesn't, open a bug report for Neovim instead.

**Comment by Hubro** [comment]
@darteil After you open Zen mode, does running this fix the gaps for you?

```vim
:lua require("zen-mode.view").fix_layout(true)
```

I have a similar issue with Neovide, I want to *increase* the font size when I enter Zen mode, so I wrote:

```
on_open = function(win)
  vim.opt.guifont = "SauceCodePro Nerd Font:h12:w57"
end,
```

This does work, but the height of the Zen floating window is all wrong. When I press `zz` to center my viewport, it's clear that the floating window extends quite a bit below my window:

![image](https://user-images.githubusercontent.com/597206/162847618-d24b7c32-dc99-439a-ad2f-8ca070ba0a75.png)

Confusingly, running `fix_layout(true)` at this point has no effect...

**Comment by darteil** [comment]
@Hubro I tried calling this command in zen mode and without zen mode

`:lua require("zen-mode.view").fix_layout(true)`

Still the same, no effect. Using a regular nvim v 0.6.1.

**Comment by darteil** [comment]
Addendum to previous post

https://user-images.githubusercontent.com/31193144/162954166-374a69c7-7b1b-4e1f-b028-38e372702a05.mp4
