### ISSUE TITLE
Option to not disable status line? Or include word count?

### ISSUE THREAD

**Issue by benfrain** [folke/zen-mode.nvim#47]
Thanks for Zen Mode, I really love it for writing prose.

One thing I built for my lualine config is a word count for when I am in txt/md files. It shows the word count for the document, or if text is selected, the words in that selection:

<img width="315" alt="image" src="https://user-images.githubusercontent.com/1318466/147659112-2bbd824f-68a5-4943-aed8-5a68056b5ae3.png">

Would you consider an option to enable a status line plugin like Lualine? Or perhaps a word count could be incorporated in Zen Mode? 

Here is the little function I use:
https://gist.github.com/benfrain/97f2b91087121b2d4ba0dcc4202d252f#file-setup-lualine-lua-L1-L13

**Comment by ivanddm** [comment]
This option would be really nice especially since Neovim now has the option to keep a global status line with `set laststatus=3`

**Comment by chrisgrieser** [comment]
I also agree that an option to keep the lualine would be very useful

**Comment by asmodeus812** [comment]
Second that, having it as an option is helpful

**Comment by felipecrp** [comment]
Also, it would be very help to keep the winbar from lualine.

**Comment by bartoszluka** [comment]
you can check out https://github.com/shortcuts/no-neck-pain.nvim it just centers the view and does not hide the status line

**Comment by felipecrp** [comment]
Thank you for the suggestion. It is not as beautiful as zen-mode, but it solves the problem.
