### ISSUE TITLE
Cursor does not jump to correct position when ZenMode is loaded with autocmd

### ISSUE THREAD

**Issue by dragon-friend** [folke/zen-mode.nvim#49]
Hello!

When using the following autocommand to turn on zenmode for a markdown file, the cursor visually appears in the wrong place relative to where it is on the current line (to the left or right of where it's supposed to be, depending on window size).

`autocmd FileType markdown :ZenMode`

edit: Running neovim 0.6.1

**Comment by pavanbhat1999** [comment]
@dragon-friend  I am experiencing the same did you find any solution ? 

@folke

**Comment by pavanbhat1999** [comment]
@dragon-friend 

` autocmd VimEnter *.wiki :ZenMode `
`autocmd VimEnter *.md :ZenMode`

**Comment by dragon-friend** [comment]
That works thanks a lot!

**Comment by nicos68** [comment]
I'm having the same issue with an ftplugin file. While the workaround does fix the issue, wouldn't it be better to support directly calling `vim.cmd.Zenmode()` ?

**Comment by Anthony-Fiddes** [comment]
I can confirm that this issue is still happening for me too. I ended up using the VimEnter autocmd too
