### ISSUE TITLE
Current line number shows are 0 when using relative line numbers

### ISSUE THREAD

**Issue by muhmud** [folke/zen-mode.nvim#50]
I'm using lunar vim and when in zen mode using relative line numbers, the current line number shows as zero.

Is there a way to get it to show the actual line number instead?

![image](https://user-images.githubusercontent.com/7550982/154787452-52d0957b-1c68-490c-8aee-29e3554bbc7b.png)

**Comment by tamton-aquib** [comment]
@muhmud probably a little late, but you'll have to turn `:set number` as well. 😅
