### ISSUE TITLE
Synchronize scroll position with the original window

### ISSUE THREAD

**Issue by Hubro** [folke/zen-mode.nvim#52]
First off, this plugin is freaking gold, well done! I have been using it full time for about a week now and I can't go back.

One thing I have noticed that tends to put a stick in my wheels is that the scroll position of my original window doesn't change. It tends to go like this:

- I need to focus on a specific window for a while, so I enter Zen mode
- I spend 5 minutes writing a bunch of code
- I now want to see my ALE Warnings and/or check the contents of a different window, so I exit Zen mode
- The scroll position I had in the Zen window is lost
- I spend 10 seconds trying to recover my scroll position, my flow completely broken :smile:
- (This is exacerbated by the fact that I unfortunately tend to work with large YANG models, which can easily be thousands of lines long)

I feel like it would be far more intuitive if the scroll position in the floating window was replicated in the original window.

This could be done continuously using the `WinScrolled` event, or the scroll position could be transferred once when Zen mode is closing.

The advantage of the former solution is that plugins that work by scroll position (such as `dstein64/nvim-scrollview`) might just work by default, since the scroll position of the original window is being updated continuously to reflect the Zen window.

**Comment by andy941** [comment]
This is very much needed, otherwise i'll say this as well: this plugin is GOLD. I like how it works seamlessly with other stuff, very clever implementation. I have no idea how much work does keeping the cursor position require on the existing code, but it would really be the cherry on top.
Thank you for the plugin anyways,
