### ISSUE TITLE
Method For Quitting When Closing ZenMode Window?

### ISSUE THREAD

**Issue by FOSSilizedDaemon** [folke/zen-mode.nvim#54]
Hello,

I use `nvim` for mostly writing not coding and am interested in using this plugin to have a more *word processor* feel when writing. The one big annoyance I have with using this plugin is that when I close the ZenMode window or use `:q` to exit it just toggles the ZenMode window instead of exiting from `nvim`. Is there any way to make it so that `nvim` exits instead of just toggling the window?

**Comment by Hubro** [comment]
What if you write `:qa`?

**Comment by philip1987** [comment]
Hi @FOSSilizedDaemon,
It's a bit of a hack but you can stick the following into your into your Zen Mode  🧘 config:
```lua
zenmode.setup({
    -- Your existing config:
    ...

    -- At the end of the file add this:
    on_open = function(_)
        vim.cmd("cabbrev <buffer> q let b:quitting = 1 <bar> q")
        vim.cmd("cabbrev <buffer> wq let b:quitting = 1 <bar> wq")
    end,
    on_close = function()
        if vim.b.quitting == 1 then
            vim.b.quitting = 0
            vim.cmd("q")
        end
    end,
})
```

This temporarily redefines :q and :wq to call the on_close function which quits out of vim for you.

**Comment by BerkeleyTrue** [comment]
I had tried "autocmd WinLeave <buffer> wqall" added in the command line options when using nvim as a word processor. The issues with this is if you open another window, for example opening up spell check, it will close the all the buffers. 

I think the above would work if it could be turned on and off. Maybe adding a command that will enable the above`ZenModeWordProcess` and then you could start vim with `nvim +"ZenModeWordProcess" +"ZenMode"`
