### ISSUE TITLE
Exiting ZenMode puts focus in the wrong window

### ISSUE THREAD

**Issue by gordonzola** [folke/zen-mode.nvim#6]
I use [vim-minimap](https://github.com/wfxr/minimap.vim), and when I enter ZenMode, the minimap is correctly hidden. But when I exit it, the focus isn’t on the same panel that it was before (ie on the only opened file)

**Comment by folke** [comment]
I'm not able to reproduce this with multiple splits open.
You mean that in your case, the minimap gets the focus?

How to do you exit ZenMode?

**Comment by folke** [comment]
It appears that minimap is taking focus to itself.

The best way to fix this is to add the following in the config:

```lua
{
...
 on_open = function(win)
     vim.cmd[[MinimapClose]]
  end,
  -- callback where you can add custom code when the Zen window closes
  on_close = function()
    vim.cmd[[Minimap]]
  end,
...
}
```

**Comment by gordonzola** [comment]
Thanks! It indeed seems that vim-minimap does weird things with focus, because with this hack, the focus gets back to my main file, except if my file explorer (NvimTree) is opened, in this case Nvim-Tree will get the focus.

**Comment by folke** [comment]
NvimTree: probably because you have follow file configured.

I'll see if I can change it so we alsways go back to the last window when closing zen mode.

**Comment by folke** [comment]
I just pushed a fix for this. This now also works without doing anything special to Minimap.

**Comment by gordonzola** [comment]
Perfect, it works without the workaround in `on_open`/`on_close`, thank you
