### ISSUE TITLE
Zenmode doesn't disable tmux status line in Alacritty with default settings

### ISSUE THREAD

**Issue by DMunkei** [folke/zen-mode.nvim#66]
Using the default setup inside of `packer.lua` doesn't disable the bottom tmux statusline  when using it inside of `Alacritty`. 
I'm using the current nvim version `v0.8.0-6`. 
```lua
use {
  "folke/zen-mode.nvim",
  config = function()
    require("zen-mode").setup {
      -- your configuration comes here
      -- or leave it empty to use the default settings
      -- refer to the configuration section below
    }
  end
}
```
[![image](https://user-images.githubusercontent.com/17084284/200343225-e003c9f1-0149-46ad-9437-7062dc955f67.png)](url)

Here's an extract from `:checkhealth` regarding tmux
```
## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=\177
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $TERM_PROGRAM='tmux'
  - INFO: $COLORTERM='truecolor'

## tmux
  - OK: escape-time: 0
  - INFO: Checking stuff
  - WARNING: `focus-events` is not enabled. |'autoread'| may not work.
    - ADVICE:
      - (tmux 1.9+ only) Set `focus-events` in ~/.tmux.conf:
          set-option -g focus-events on
  - INFO: $TERM: tmux-256color
```
Hope this helps, if there is anything else I might provide let me know.

**Comment by syfless1999** [comment]
+1

**Comment by sjonpaulbrown** [comment]
I'm unsure where the issue is at within the plugin, but the following workaround works for me. This disables the status line and hides the panes. It will restore the status and panes on exit. The system commands were referenced from the plugin itself.

I'm using Alacritty, and as this is calling the commands directly, it should work with other terminal emulators as well.

```
require('zen-mode').setup({
    on_open = function(_)
        vim.fn.system([[tmux set status off]])
        vim.fn.system(
            [[tmux list-panes -F '\#F' | grep -q Z || tmux resize-pane -Z]])
    end,
    on_close = function(_)
        vim.fn.system([[tmux set status on]])
        vim.fn.system(
            [[tmux list-panes -F '\#F' | grep -q Z && tmux resize-pane -Z]])
    end
})
```
