### ISSUE TITLE
`cmdheight=0` causes problems

### ISSUE THREAD

**Issue by aleprovencio** [folke/zen-mode.nvim#69]
When using `cmdgheight=0`, and activating `zen-mode`, there are parts of the status line left on the screen and also a wrong line above the its window.

It seems that `zen-mode`'s window should be drawn one line above.

**Comment by eXvimmer** [comment]
I have the same issue. When cmdheight is set to zero, lualine will remain under the main buffer.

**Comment by eXvimmer** [comment]
@folke here's the screenshot
![cmdheight](https://user-images.githubusercontent.com/30720669/210609492-1abb6803-d15b-4c17-88c5-2de433a95fcc.png)

**Comment by Rishabh672003** [comment]
yeah this issue persists when used with https://github.com/folke/noice.nvim as cmdheight is always 0 there
@folke can you please look in to this thanks for your awesome work

**Comment by eXvimmer** [comment]
Hi @folke 
Do you have any plans for fixing this? Is this even fixable?

**Comment by eXvimmer** [comment]
I fixed it like this

```lua
local lualine = require("lualine")

require("zen-mode").setup({
	on_open = function(win)
		lualine.hide()
		vim.o.statusline = " "
	end,
	on_close = function()
		lualine.hide({ unhide = true })
	end,
})
```

**Comment by Rishabh672003** [comment]
@eXvimmer well it is a work around and not a fix
![image](https://user-images.githubusercontent.com/53911515/215121345-17bd073c-bd7b-4ef7-99bd-1fb52602ad3f.png) you can see the black bar still in the bottom

**Comment by folke** [comment]
You can set `config.plugins.options.laststatus = 0`, but there's seems to be a bug in Neovim, that does not allow the height of the background window to be full height.

**Comment by eXvimmer** [comment]
@folke Yes, `:h cmdheight` says that cmdheight=0 is considered experimental.
Thank you for creating this useful plugin.

**Comment by eXvimmer** [comment]
@Rishabh672003 If it bothers you, then I think you can find the highlight group of the cmd and change it.

**Comment by folke** [comment]
@eXvimmer that's not the problem. As I mentioned, there's a bug in Neovim nightly that can't display a window full height. A window can render over the bottom part, if you set `row=1`, so just a bug.

**Comment by eXvimmer** [comment]
@folke OK. Thanks!

**Comment by eXvimmer** [comment]
@folke Can you add an event listener like `on_buffer_change` (like on_open/on_close) that runs a function when zen-mode is active, and we run `:bnext` or `:bprev`?

**Comment by eXvimmer** [comment]
BTW, the best solution for me is this.

```lua
local lualine = require("lualine")

require("zen-mode").setup({
	on_open = function(win)
		lualine.hide({})
		-- vim.o.statusline = ""
		vim.o.cmdheight = 1
	end,
	on_close = function()
		vim.o.cmdheight = 0
		lualine.hide({ unhide = true })
	end,
})
```

**Comment by imNel** [comment]
<img width="588" alt="image" src="https://user-images.githubusercontent.com/46218259/234079365-9d179723-7cbc-4cf1-97fb-525df49e202f.png">
Fixed with nvim v0.9.0?

**Comment by Rishabh672003** [comment]
Yeah seems like this is fixed in nvim-0.9, other than the top having 3 blank lines but the bottom having 2
![image](https://user-images.githubusercontent.com/53911515/234230168-90ab043e-fb78-4cfb-85c1-e1d7b9d0a7bb.png)

**Comment by aleprovencio** [comment]
Yeap, `0.9` also fixes for me, thanks for this

**Comment by diegoulloao** [comment]
> BTW, the best solution for me is this.
> 
> ```lua
> -- local lualine = require("lualine")
> 
> require("zen-mode").setup({
> 	on_open = function(win)
> 		-- lualine.hide({})
> 		-- vim.o.statusline = ""
> 		vim.o.cmdheight = 1
> 	end,
> 	on_close = function()
> 		vim.o.cmdheight = 0
> 		-- lualine.hide({ unhide = true })
> 	end,
> })
> ```

this worked for me!

**Comment by danielyrovas** [comment]
For anyone that ends up here, I found setting laststatus to work much better than cmdheight
```lua
on_open = function(_)
    vim.o.laststatus = 2
    require("lualine").hide()
end,
on_close = function()
    vim.o.laststatus = 3
    require("lualine").hide { unhide = true }
end,
```
