### ISSUE TITLE
Options passed to `toggle()` are not set

### ISSUE THREAD

**Issue by gordonzola** [folke/zen-mode.nvim#7]
I’ve set default options for Zen Mode in my lua config, and a special call to `require("zen-mode").toggle()` for a special prose writing mode. However, when I use this mode, it seems that the only options set are the default ones.

Here’s an extract of my config:

```lua
map("n", "<leader>z", [[ <Cmd> ZenMode<CR>]], opt)
-- Writing mode
local writing_mode = false

function toggle_writing_mode()
  require("zen-mode").toggle({
    window = {width = 100},
    options = {signcolumn = "no", linebreak = true, cursorline = false, colorcolumn = false, spell=true},
  })
  if writing_mode then
    base16(base16.themes["solarized-dark"], true)
    set_highlights()
    writing_mode = false
  else
    base16(base16.themes["solarized-light"], true)
    writing_mode = true
  end
end

map("n", "<leader>Z", [[ <Cmd> lua toggle_writing_mode()<CR>]], opt)

-- Zenmode
require("zen-mode").setup {
  plugins = {
    kitty =  {
      enabled = true,
      font = "+2"
    }
  },
}
```

When using the `toggle_writing_mode` function, the colorscheme is correctly applied, but none of the `options` in the `toggle()` call. However, the custom width is applied.

**Comment by folke** [comment]
options should be under window. Please check the docs.

**Comment by gordonzola** [comment]
Thanks, i missed that >_<
