### ISSUE TITLE
Dimmed area isn't transparent

### ISSUE THREAD

**Issue by I60R** [folke/zen-mode.nvim#70]
I've tried to tweak `backdrop` but it seems that there's no effect whatsoever.

Also, I've tried `hi ZenBg ctermbg=NONE` but there's no effect.

This is how Zen mode currently looks:

![Screenshot@2022-11-22@22:39:03](https://user-images.githubusercontent.com/9143774/203426652-b98109d0-a0f3-4a68-b3c7-96d88fe7bacb.png)

That said, I want it to be transparent accordingly to my color scheme

**Comment by alexanderstephan** [comment]
Using `vim.api.nvim_set_hl(0, "ZenBg", { ctermbg = 0 })` worked for me. One thing that could go wrong is that you set your colortheme after you run this command, so it might get overwritten. 🤔

**Comment by I60R** [comment]
Works for me as well, I don't know what's the difference with `hi`

**Comment by Aqa-Ib** [comment]
This line of code works for me:
`vim.cmd("autocmd VimEnter * hi ZenBg ctermbg=NONE guibg=NONE")
`
