### ISSUE TITLE
Zenmode doesn't restore tmux status line in Alacritty with default settings

### ISSUE THREAD

**Issue by disidrosi** [folke/zen-mode.nvim#71]
Perhaps related to #66.

Tmux status line is not restored in Alacritty when exiting Zenmode.

![Screen Recording 2022-11-24 at 13 33 27 (3)](https://user-images.githubusercontent.com/26408944/203789177-7d0df67d-f8a5-426c-b98f-cf7ed0c9fc87.gif)

Zenmode plugin configuration:
```lua
require('zen-mode').setup {
  plugins = {
    tmux = { enabled = true },
  },
}
```

`:checkhealth` info:
```
## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=\177
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $TERM_PROGRAM='tmux'
  - INFO: $COLORTERM='truecolor'

## tmux
  - OK: escape-time: 10
  - INFO: Checking stuff
  - OK: focus-events: on
  - INFO: $TERM: tmux-256color
```

`nvim -v` info:
```
NVIM v0.8.1
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@Ventura-arm64.local
```

**Comment by XXiaoA** [comment]
Same bug in wezterm. It's seems that it's a bug of https://github.com/folke/zen-mode.nvim/commit/6f5702db4fd4a4c9a212f8de3b7b982f3d93b03c

**Comment by disidrosi** [comment]
Just tested and the the bug seems to be fixed. Thank you very much!

**Comment by crivotz** [comment]
Problem is still active under wezterm

**Comment by XXiaoA** [comment]
> Problem is still active under Wezterm


just try my fork
https://github.com/folke/zen-mode.nvim/pull/72

**Comment by clue44** [comment]
This bug is also in Kitty for me. The tmux statusline disappears when going into zen mode, but doesnt come back when going out of zen mode.

**Comment by evantravers** [comment]
I'm in Kitty, still the same thing.
