### ISSUE TITLE
Feature request: add an option to set vertical padding

### ISSUE THREAD

**Issue by mroavi** [folke/zen-mode.nvim#73]
It would be nice to have the option to set the number of (virtual) blank lines that are displayed above/below the first/last lines of the buffer that is being displayed (this is what I refer to as vertical padding). I noticed that Goyo has this as default:

**goyo**:

![image](https://user-images.githubusercontent.com/19517248/206913811-27eeb8c8-eda1-4e6b-8fb4-b91883e65cbd.png)

**zen-mode**:

![image](https://user-images.githubusercontent.com/19517248/206914339-38e86d43-d934-43b1-a90f-78c1c7a951f1.png)

**Comment by miguno** [comment]
ping

**Comment by b0ae989c** [comment]
This is already achievable without new features. Try
```lua
opts = {
  window = {
    height = function()
      return vim.api.nvim_win_get_height(0) - 2
    end,
  },
}
```
