### ISSUE TITLE
 Hope you can inform me about the highlighting plugin in your screenshot

### ISSUE THREAD

**Issue by Coien-rr** [folke/zen-mode.nvim#75]
![f09db7e65206d6434ccdf7572a32c2a](https://user-images.githubusercontent.com/83146518/211567855-27229deb-d23a-4235-965f-00d0ab6b0edf.jpg)

Hope you can inform me about the highlighting plugin in your screenshot
thank you very much！！

**Comment by folke** [comment]
indent-blankline
