### ISSUE TITLE
bug: Zen-Mode backdrop does not work properly with colorscheme

### ISSUE THREAD

**Issue by Abhi6** [folke/zen-mode.nvim#76]
### Did you check docs and existing issues?

- [X] I have read all the zen-mode.nvim docs
- [X] I have searched the existing issues of zen-mode.nvim
- [X] I have searched the exsiting issues of plugins related to this issue

### Neovim version (nvim -v)

0.8.1

### Operating system/version

MacOS 12.6 Monterey

### Describe the bug

The backdrop of my screen when entering Zen-Mode does not fully reach the bottom of my screen. This happens only when I am using the everforest colorscheme and works fine if I use another one like nightfox. The link directs to the video.
https://www.veed.io/embed/72436a9d-7b3d-4a5d-bccd-4a5c941577db
I would like to know if there are any changes that must be made in order for zen-mode to be compatible with everforest.

### Steps To Reproduce

The default configuration for zen-mode and using the everforest colorscheme.

### Expected Behavior

The backdrop is a full column from the top of the editor to the bottom

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")
-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "neanias/everforest-nvim",
  "folke/zen-mode.nvim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("everforest")
-- add anything else here
```

**Comment by WieeRd** [comment]
@Abhi6 It looks like my PR #78 can fix this issue as well.
