### ISSUE TITLE
[Request] Remove global for `tmux set status off `

### ISSUE THREAD

**Issue by surmish** [folke/zen-mode.nvim#8]
I have 2 tmux sessions open. When I enter `tmux set -g status off` in one of the sessions (outside of nvim), it doesn't switch off tmux status.
However, `tmux set status off` does work.

Would it be right to make that change from the plugin in zen-mode too? I removed `-g` from the plugins.lua in the zen-mode plugin and that does make the status line enable/disable as expected.

**Comment by folke** [comment]
You are correct. The `-g` global switch should not be in there. I just pushed a fix.
