### ISSUE TITLE
feature: add mapping to toggle full window width

### ISSUE THREAD

**Issue by mikehaertl** [folke/zen-mode.nvim#82]
### Did you check the docs?

- [X] I have read all the zen-mode.nvim docs

### Is your feature request related to a problem? Please describe.

While a window width of 120 is perfect for most code it would be nice to toggle to full width when checking a log file.

### Describe the solution you'd like

I suggest a key mapping like `f` to toggle full width. The mapping should be restricted to the zen window.

### Describe alternatives you've considered

I've tried to add a mapping via `on_open` but I failed due to 2 problems:

 * I don't know how to change `window.width` config while the window is open
 * I don't know how to restrict the mapping to the zen window. I can only restrict it to the buffer but then the `f` mapping is also still active when the zen window is closed.

**Comment by mikehaertl** [comment]
This is a comment to avoid closing :-/

**Comment by mikehaertl** [comment]
This is another comment to avoid closing :-/

**Comment by mikehaertl** [comment]
.

**Comment by mikehaertl** [comment]
.

**Comment by mikehaertl** [comment]
!

**Comment by asilvadesigns** [comment]
.

**Comment by majordoobie** [comment]
👋

**Comment by mikehaertl** [comment]
@majordoobie Well you're basically just configuring the `width`. What I wanted was a way to toggle the width while in zen-mode, e.g. from `120` (for a nice centered view) to `1` (==100%) for full width.

**Comment by majordoobie** [comment]
> @majordoobie Well you're basically just configuring the `width`. What I wanted was a way to toggle the width while in zen-mode, e.g. from `120` (for a nice centered view) to `1` (==100%) for full width.

The toggle I made disables zen, doesn't that do the same thing? Gives you 100% of your view.

**Comment by mikehaertl** [comment]
Not sure I can follow: I already have a mapping for `:ZenMode`. So I can already activate/deactivate Zen mode.

But what I want is, when zen mode is active I still want more control over the window width. E.g. I want to go from 120 width to 100% width (and back).
