### ISSUE TITLE
bug: Alacritty font size change not work

### ISSUE THREAD

**Issue by dongdongbh** [folke/zen-mode.nvim#84]
### Did you check docs and existing issues?

- [X] I have read all the zen-mode.nvim docs
- [X] I have searched the existing issues of zen-mode.nvim
- [X] I have searched the exsiting issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.8.3-dev-6+g5d5a15568

### Operating system/version

ubuntu 20.04 server

Alacritty version: 0.11.0

### Describe the bug

Alacritty font size change not work.

My config
``` lua
require("zen-mode").setup {
  window = {
    backdrop = 0.95, -- shade the backdrop of the Zen window. Set to 1 to keep the same as Normal
    -- height and width can be:
    -- * an absolute number of cells when > 1
    -- * a percentage of the width / height of the editor when <= 1
    -- * a function that returns the width or the height
    width = .7, -- width of the Zen window
    height = 1, -- height of the Zen window
    -- by default, no options are changed for the Zen window
    -- uncomment any of the options below, or add other vim.wo options you want to apply
    options = {
      -- signcolumn = "no", -- disable signcolumn
      -- number = false, -- disable number column
      -- relativenumber = false, -- disable relative numbers
      -- cursorline = false, -- disable cursorline
      -- cursorcolumn = false, -- disable cursor column
      -- foldcolumn = "0", -- disable fold column
      -- list = false, -- disable whitespace characters
    },
  },
  gitsigns = { enabled = false }, -- disables git signs
  plugins = {
    tmux = { enabled = true },
  },
  alacritty = {
    enabled = true,
    font = "14", -- font size
  },
}
```

### Steps To Reproduce

change `font` size in
```lua
alacritty = {
    enabled = true,
    font = "14", -- font size
  },
```
e.g. change to font = "20"
`:ZenMode` font size not change.

### Expected Behavior

change the font size on alacritty when in zen mode

**Comment by mendes-davi** [comment]
Hi, are you using tmux?

**Comment by dongdongbh** [comment]
I test it in both plain alacritty and tmux, the `alacritty msg` command works, but in nvim zenmode it not work.

**Comment by mendes-davi** [comment]
I had some issue inside tmux with the environment variable `ALACRITTY_WINDOW_ID` not being updated properly and had to set my tmux.conf in order for it to work. 

```
set-option -g update-environment "ALACRITTY_LOG \
                                  ALACRITTY_WINDOW_ID \
                                  ALACRITTY_SOCKET"
```

> I test it in both plain alacritty and tmux, the alacritty msg command works, but in nvim zenmode it not work.

That's odd. In neovim, test for `:echo executable("alacritty")`. It should be `1`. Besides that, idk what could be the problem.

**Comment by dongdongbh** [comment]
Yes, it is `:echo executable("alacritty")` is one, it's strange~

**Comment by mendes-davi** [comment]
I just noticed your config is wrong... It should be:

```
plugins = {
    tmux = { enabled = true },
    alacritty = {
        enabled = true,
        font = "14", -- font size
    },
},
```

The `alacritty` key needs to be nested inside `plugins`. That should fix it!

**Comment by dongdongbh** [comment]
Oh, yes, it works, thank you for pointing out that
