### ISSUE TITLE
feature: add plugin to disable Indent Blankline

### ISSUE THREAD

**Issue by dm9pZCAq** [folke/zen-mode.nvim#88]
### Did you check the docs?

- [X] I have read all the zen-mode.nvim docs

### Is your feature request related to a problem? Please describe.

I'm always frustrated when there is Indent Blankline enabled in zen-mode

### Describe the solution you'd like

add plugin option for blankline:
```lua
{
  -- ...
  plugins = {
    indent_blankline = { enabled = false },
  },
  -- ...
}
```

### Describe alternatives you've considered

add some indication to floating window to get it and disable Indent Blankline with their own methods like [is_indent_blankline_enabled](https://github.com/lukas-reineke/indent-blankline.nvim/blob/018bd04d80c9a73d399c1061fa0c3b14a7614399/lua/indent_blankline/init.lua#L153-L165)

**Comment by Di-az** [comment]
I know it's not the feature you are asking for, but a way you could toggle `indent_blankline` is through the `on_open` and `on_close` methods:

```lua
require("zenmode").setup({
    --Your config

    on_open = function()
        vim.cmd("IndentBlanklineDisable")
    end,
    on_close = function()
        vim.cmd("IndentBlanklineEnable")
    end,
})
```
