### ISSUE TITLE
Can't install it using paq

### ISSUE THREAD

**Issue by hrqmonteiro** [folke/zen-mode.nvim#9]
I use [paq](https://github.com/savq/paq-nvim), and when i try to install it, i have this error:

`Paq [ ] failed to parse zen-mode.nvim`

**Comment by folke** [comment]
do you have Neovim >= 0.5?

**Comment by hrqmonteiro** [comment]
Yes, i do. Actually just changed for the newer build due to the z-index feature.

I installed the plugin manually, and it's running fine, my only concern is why it didn't work with paq, since i install all the plugins using it.

**Comment by folke** [comment]
No idea. I use Packer myself.
Maybe try reinstalling the plugin?

**Comment by folke** [comment]
You add my github name to the package right?

```lua
paq 'folke/zen-mode.nvim'
```
