### ISSUE TITLE
bug: error with trouble.nvim when toggling it in zen-mode

### ISSUE THREAD

**Issue by johannesrld** [folke/zen-mode.nvim#94]
### Did you check docs and existing issues?

- [X] I have read all the zen-mode.nvim docs
- [X] I have searched the existing issues of zen-mode.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.0

### Operating system/version

Windows

### Describe the bug

If you enter trouble.nvim using :TroubleToggle, then go in to zen mode, and activate :TroubleToggle once again to exit it will crash with this message

```
Error detected while processing WinClosed Autocommands for "1022":
E5108: Error executing lua ...Local/nvim-data/lazy/zen-mode.nvim/lua/zen-mode/view.lua:47: Invalid window id: 1019
stack traceback:
        [C]: in function 'nvim_win_get_buf'
        ...Local/nvim-data/lazy/zen-mode.nvim/lua/zen-mode/view.lua:47: in function 'close'
        [string ":lua"]:1: in main chunk
        [C]: in function 'nvim_buf_delete'
        ...a/Local/nvim-data/lazy/trouble.nvim/lua/trouble/view.lua:344: in function 'close'
        ...a/Local/nvim-data/lazy/trouble.nvim/lua/trouble/init.lua:28: in function 'close'
        ...a/Local/nvim-data/lazy/trouble.nvim/lua/trouble/init.lua:96: in function 'toggle'
        [string ":lua"]:1: in main chunk
```

I'm not sure if this issue is better in zen-modes or troubles issue tracker, but since it the first error mentioned is in zen-modes code and both plugins are maintained by you i figured it was best opened here.

### Steps To Reproduce

1. enter nvim/buffer
2. Activate Trouble using `:TroubleToggle`
3. enter zen mode
4. Deactivate Trouble using `:TroubleToggle`

### Expected Behavior

Honestly no idea, i guess just return to a state where both extensions are deactivated? or maybe just refuse to activate in the trouble buffer to begin with?

**Comment by piotr-marendowski** [comment]
Are you entering Trouble and toggling on the Zen Mode when focused on Trouble? If yes then why? It has to do something with Trouble not being an ordinary buffer (I think) and Zen Mode being your current buffer - floating and overlaying the whole screen.

**Comment by folke** [comment]
yeah, that indeed wouldn't work. Closing...
